name: andrew_premium_ui
description: Premium Flutter UI for Project Andrew
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^2.4.0
  google_fonts: ^6.1.0
  glassmorphism: ^3.0.0
  flutter_tts: ^3.8.3
  speech_to_text: ^6.5.1
  flutter_animate: ^4.2.0+1
  scroll_loop_auto_scroll: ^0.0.3
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
